#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

try {
    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->load();
    

} catch (\Exception $e) {
    echo "Error loading .env file: " . $e->getMessage() . "\n";
    exit(1);
}

require_once __DIR__ . '/core/Database.php';
require_once __DIR__ . '/core/Migration.php';
require_once __DIR__ . '/console/Migrate.php';

$migrator = new console\Migrate();

if (isset($argv[1]) && $argv[1] === 'rollback') {
    $migrator->rollback();
} else {
    $migrator->run();
}
